# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counter', '0008_auto_20170122_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='telegram_chat_id')),
                ('notify_only_members', models.BooleanField(verbose_name='notify_only_members')),
            ],
            options={
                'verbose_name': 'telegram_chat',
                'verbose_name_plural': 'telegram_chats',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True, verbose_name='telegram_user_id')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Counter', verbose_name='counter')),
            ],
            options={
                'verbose_name': 'telegram_user',
                'verbose_name_plural': 'telegram_users',
            },
        ),
        migrations.CreateModel(
            name='TelegramUserChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='telegram_user_id')),
                ('telegram_chat_id', models.BigIntegerField(verbose_name='telegram_chat_id')),
            ],
            options={
                'verbose_name': 'telegram_user_chat',
                'verbose_name_plural': 'telegram_user_chats',
            },
        ),
        migrations.CreateModel(
            name='TelegramUserCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='telegram_user_id')),
                ('verif_key', models.TextField(unique=True, verbose_name='verify_key')),
            ],
            options={
                'verbose_name': 'telegram_user_check',
                'verbose_name_plural': 'telegram_user_checks',
            },
        ),
        migrations.AlterUniqueTogether(
            name='telegramuserchat',
            unique_together=set([('telegram_user_id', 'telegram_chat_id')]),
        ),
    ]
