# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nom')),
                ('lastReset', models.DateTimeField(verbose_name='Dernière remise à zéro')),
            ],
            options={
                'verbose_name': 'Compteur',
            },
        ),
    ]
