# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('reason', models.TextField(verbose_name='Raison')),
            ],
        ),
        migrations.RemoveField(
            model_name='counter',
            name='lastReset',
        ),
        migrations.AddField(
            model_name='counter',
            name='trigramme',
            field=models.CharField(default='AAA', max_length=3, verbose_name='Trigramme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reset',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Counter'),
        ),
    ]
