# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20160314_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reset',
            options={'verbose_name': 'Remise à zéro', 'verbose_name_plural': 'Remises à zéro'},
        ),
        migrations.AddField(
            model_name='counter',
            name='email',
            field=models.EmailField(default='null@localhost', max_length=264, verbose_name='Email'),
        ),
    ]
