# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counter', '0003_auto_20161208_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='email_notifications',
            field=models.BooleanField(default=False, verbose_name='Notifications par email'),
        ),
        migrations.AddField(
            model_name='counter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reset',
            name='who',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who', to='counter.Counter'),
        ),
        migrations.AlterField(
            model_name='reset',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='counter.Counter'),
        ),
    ]
