# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_auto_20170103_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='sort_by_score',
            field=models.BooleanField(default=True, verbose_name='trier par SeumScore™'),
        ),
    ]
