# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_auto_20170113_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': 'counter'},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'hashtag', 'verbose_name_plural': 'hashtags'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'keyword', 'verbose_name_plural': 'keywords'},
        ),
        migrations.AlterModelOptions(
            name='reset',
            options={'verbose_name': 'reset', 'verbose_name_plural': 'resets'},
        ),
        migrations.AlterField(
            model_name='counter',
            name='email_notifications',
            field=models.BooleanField(default=False, verbose_name='email notifications'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='sort_by_score',
            field=models.BooleanField(default=True, verbose_name='sort by SeumScore'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='trigramme',
            field=models.CharField(max_length=3, verbose_name='trigram'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='associated user'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='counter.Keyword', verbose_name='hashtag'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='reset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='counter.Reset', verbose_name='reset'),
        ),
        migrations.AlterField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='counter.Counter', verbose_name='liker'),
        ),
        migrations.AlterField(
            model_name='like',
            name='reset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='counter.Reset', verbose_name='seum'),
        ),
        migrations.AlterField(
            model_name='like',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime'),
        ),
        migrations.AlterField(
            model_name='reset',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to='counter.Counter', verbose_name='victim'),
        ),
        migrations.AlterField(
            model_name='reset',
            name='reason',
            field=models.TextField(verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='reset',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime'),
        ),
        migrations.AlterField(
            model_name='reset',
            name='who',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who', to='counter.Counter', verbose_name='seum giver'),
        ),
    ]
